"""add_timezone_to_students

Revision ID: 31f8ae0dba64
Revises: 7befe7226af8
Create Date: 2026-09-19 14:40:40.524798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31f8ae0dba64'
down_revision: Union[str, Sequence[str], None] = '7befe7226af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('timezone', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'timezone')
    # ### end Alembic commands ###
